# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/daniel/Documents/Mes Sources/Python/PycharmProjects/00 - Personnels/Guic2py/Guic2py_dialog1.ui'
#
# Created: Thu Sep 17 09:45:31 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 500)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(400, 500))
        Dialog.setMaximumSize(QtCore.QSize(400, 500))
        Dialog.setWindowOpacity(9.0)
        Dialog.setSizeGripEnabled(True)
        self.line_SrcDir = QtGui.QLineEdit(Dialog)
        self.line_SrcDir.setGeometry(QtCore.QRect(30, 250, 251, 27))
        self.line_SrcDir.setObjectName("line_SrcDir")
        self.lbl_SrcDir = QtGui.QLabel(Dialog)
        self.lbl_SrcDir.setGeometry(QtCore.QRect(20, 230, 231, 20))
        self.lbl_SrcDir.setObjectName("lbl_SrcDir")
        self.lbl_SrcFile = QtGui.QLabel(Dialog)
        self.lbl_SrcFile.setGeometry(QtCore.QRect(20, 280, 231, 20))
        self.lbl_SrcFile.setObjectName("lbl_SrcFile")
        self.line_SrcFile = QtGui.QLineEdit(Dialog)
        self.line_SrcFile.setGeometry(QtCore.QRect(30, 300, 251, 27))
        self.line_SrcFile.setText("")
        self.line_SrcFile.setMaxLength(32767)
        self.line_SrcFile.setPlaceholderText("")
        self.line_SrcFile.setObjectName("line_SrcFile")
        self.btn_SelSrcDirFile = QtGui.QPushButton(Dialog)
        self.btn_SelSrcDirFile.setGeometry(QtCore.QRect(290, 250, 85, 81))
        self.btn_SelSrcDirFile.setObjectName("btn_SelSrcDirFile")
        self.btn_SelDstDir = QtGui.QPushButton(Dialog)
        self.btn_SelDstDir.setGeometry(QtCore.QRect(290, 365, 85, 41))
        self.btn_SelDstDir.setObjectName("btn_SelDstDir")
        self.lbl_DstDir = QtGui.QLabel(Dialog)
        self.lbl_DstDir.setGeometry(QtCore.QRect(20, 350, 231, 20))
        self.lbl_DstDir.setObjectName("lbl_DstDir")
        self.lbl_DstFile = QtGui.QLabel(Dialog)
        self.lbl_DstFile.setGeometry(QtCore.QRect(20, 400, 231, 20))
        self.lbl_DstFile.setObjectName("lbl_DstFile")
        self.line_DstDir = QtGui.QLineEdit(Dialog)
        self.line_DstDir.setGeometry(QtCore.QRect(30, 370, 251, 27))
        self.line_DstDir.setObjectName("line_DstDir")
        self.line_DstFile = QtGui.QLineEdit(Dialog)
        self.line_DstFile.setGeometry(QtCore.QRect(30, 420, 251, 27))
        self.line_DstFile.setObjectName("line_DstFile")
        self.btn_Go = QtGui.QPushButton(Dialog)
        self.btn_Go.setGeometry(QtCore.QRect(30, 470, 161, 26))
        self.btn_Go.setObjectName("btn_Go")
        self.btn_Quit = QtGui.QPushButton(Dialog)
        self.btn_Quit.setGeometry(QtCore.QRect(300, 470, 71, 26))
        self.btn_Quit.setObjectName("btn_Quit")
        self.line_UtilLocation = QtGui.QLineEdit(Dialog)
        self.line_UtilLocation.setGeometry(QtCore.QRect(30, 90, 251, 27))
        self.line_UtilLocation.setObjectName("line_UtilLocation")
        self.lbl_UtilParams = QtGui.QLabel(Dialog)
        self.lbl_UtilParams.setGeometry(QtCore.QRect(20, 120, 321, 20))
        self.lbl_UtilParams.setObjectName("lbl_UtilParams")
        self.line_UtilParams = QtGui.QLineEdit(Dialog)
        self.line_UtilParams.setGeometry(QtCore.QRect(30, 140, 251, 27))
        self.line_UtilParams.setObjectName("line_UtilParams")
        self.btn_SelUtil = QtGui.QPushButton(Dialog)
        self.btn_SelUtil.setGeometry(QtCore.QRect(290, 90, 85, 26))
        self.btn_SelUtil.setObjectName("btn_SelUtil")
        self.lbl_UtilLocation = QtGui.QLabel(Dialog)
        self.lbl_UtilLocation.setGeometry(QtCore.QRect(20, 70, 321, 20))
        self.lbl_UtilLocation.setObjectName("lbl_UtilLocation")
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(20, 210, 351, 16))
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(20, 450, 351, 16))
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(4)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(20, 330, 351, 16))
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(0)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.frame = QtGui.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 30, 381, 41))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(3)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtGui.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 10, 279, 24))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rad_pyqt4 = QtGui.QRadioButton(self.layoutWidget)
        self.rad_pyqt4.setObjectName("rad_pyqt4")
        self.horizontalLayout.addWidget(self.rad_pyqt4)
        self.rad_pyside = QtGui.QRadioButton(self.layoutWidget)
        self.rad_pyside.setObjectName("rad_pyside")
        self.horizontalLayout.addWidget(self.rad_pyside)
        self.rad_Perso = QtGui.QRadioButton(self.layoutWidget)
        self.rad_Perso.setObjectName("rad_Perso")
        self.horizontalLayout.addWidget(self.rad_Perso)
        self.lbl_interpreteur = QtGui.QLabel(Dialog)
        self.lbl_interpreteur.setGeometry(QtCore.QRect(20, 10, 361, 17))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.lbl_interpreteur.setFont(font)
        self.lbl_interpreteur.setObjectName("lbl_interpreteur")
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 170, 351, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 190, 351, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_APropos = QtGui.QPushButton(Dialog)
        self.btn_APropos.setGeometry(QtCore.QRect(200, 470, 91, 26))
        self.btn_APropos.setObjectName("btn_APropos")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.line_UtilLocation, self.line_UtilParams)
        Dialog.setTabOrder(self.line_UtilParams, self.btn_SelUtil)
        Dialog.setTabOrder(self.btn_SelUtil, self.line_SrcDir)
        Dialog.setTabOrder(self.line_SrcDir, self.line_SrcFile)
        Dialog.setTabOrder(self.line_SrcFile, self.line_DstDir)
        Dialog.setTabOrder(self.line_DstDir, self.line_DstFile)
        Dialog.setTabOrder(self.line_DstFile, self.btn_SelSrcDirFile)
        Dialog.setTabOrder(self.btn_SelSrcDirFile, self.btn_SelDstDir)
        Dialog.setTabOrder(self.btn_SelDstDir, self.btn_Go)
        Dialog.setTabOrder(self.btn_Go, self.btn_Quit)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Guic2py", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_SrcDir.setText(QtGui.QApplication.translate("Dialog", "Répertoire source", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_SrcFile.setText(QtGui.QApplication.translate("Dialog", "Nom du fichier source", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_SelSrcDirFile.setText(QtGui.QApplication.translate("Dialog", "Choisir", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_SelDstDir.setText(QtGui.QApplication.translate("Dialog", "Choisir", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_DstDir.setText(QtGui.QApplication.translate("Dialog", "Répertoire cible", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_DstFile.setText(QtGui.QApplication.translate("Dialog", "Nom du fichier cible", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_Go.setText(QtGui.QApplication.translate("Dialog", "Convertir", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_Quit.setText(QtGui.QApplication.translate("Dialog", "Quitter", None, QtGui.QApplication.UnicodeUTF8))
        self.line_UtilLocation.setText(QtGui.QApplication.translate("Dialog", "/usr/bin/pyuic4", None, QtGui.QApplication.UnicodeUTF8))
        self.line_UtilLocation.setPlaceholderText(QtGui.QApplication.translate("Dialog", "ex: /usr/bin/pyuic4            Cliquez ->", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_UtilParams.setText(QtGui.QApplication.translate("Dialog", "Paramêtres de l\'utilitaire de conversion", None, QtGui.QApplication.UnicodeUTF8))
        self.line_UtilParams.setText(QtGui.QApplication.translate("Dialog", "{SRC} -o {DST}", None, QtGui.QApplication.UnicodeUTF8))
        self.line_UtilParams.setPlaceholderText(QtGui.QApplication.translate("Dialog", "ex. {SRC} -o {DST}", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_SelUtil.setText(QtGui.QApplication.translate("Dialog", "Choisir", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_UtilLocation.setText(QtGui.QApplication.translate("Dialog", "Localisation de l\'utilitaire de conversion", None, QtGui.QApplication.UnicodeUTF8))
        self.rad_pyqt4.setText(QtGui.QApplication.translate("Dialog", "PyQt4", None, QtGui.QApplication.UnicodeUTF8))
        self.rad_pyside.setText(QtGui.QApplication.translate("Dialog", "PySide", None, QtGui.QApplication.UnicodeUTF8))
        self.rad_Perso.setText(QtGui.QApplication.translate("Dialog", "Personalisé", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_interpreteur.setText(QtGui.QApplication.translate("Dialog", "Choisir un convertisseur", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "{SRC} ->  pour le chemin de la source.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "{DST} -> pour le chemin de la destination.", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_APropos.setText(QtGui.QApplication.translate("Dialog", "À propos", None, QtGui.QApplication.UnicodeUTF8))

